# Data Preparation

## Import Libraries

In [2]:
import numpy as np
import pandas as pd

## Import Data
The dataset contains all available data for more than 800,000 consumer loans issued from 2007 to 2015 by Lending Club: a large US peer-to-peer lending company. There are several different versions of this dataset. We have used a version available on kaggle.com. You can find it here: https://www.kaggle.com/wendykan/lending-club-loan-data/version/1
We divided the data into two periods because we assume that some data are available at the moment when we need to build Expected Loss models, and some data comes from applications after. Later, we investigate whether the applications we have after we built the Probability of Default (PD) model have similar characteristics with the applications we used to build the PD model.

In [3]:
loan_data_backup = pd.read_csv('loan_data_2007_2014.csv')

C:\Users\Shreya\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3020: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [4]:
loan_data = loan_data_backup.copy()

## Explore Data

In [5]:
loan_data

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,...,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
0,0,1077501,1296599,5000,5000,4975.00000,36 months,10.65,162.87,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1077430,1314167,2500,2500,2500.00000,60 months,15.27,59.83,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,1077175,1313524,2400,2400,2400.00000,36 months,15.96,84.33,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,1076863,1277178,10000,10000,10000.00000,36 months,13.49,339.31,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,1075358,1311748,3000,3000,3000.00000,60 months,12.69,67.79,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5,1075269,1311441,5000,5000,5000.00000,36 months,7.90,156.46,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,6,1069639,1304742,7000,7000,7000.00000,60 months,15.96,170.08,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,7,1072053,1288686,3000,3000,3000.00000,36 months,18.64,109.43,E,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,8,1071795,1306957,5600,5600,5600.00000,60 months,21.28,152.39,F,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,9,1071570,1306721,5375,5375,5350.00000,60 months,12.69,121.45,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,10,1070078,1305201,6500,6500,6500.00000,60 months,14.65,153.45,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,11,1069908,1305008,12000,12000,12000.00000,36 months,12.69,402.54,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,12,1064687,1298717,9000,9000,9000.00000,36 months,13.49,305.38,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,13,1069866,1304956,3000,3000,3000.00000,36 months,9.91,96.68,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,14,1069057,1303503,10000,10000,10000.00000,36 months,10.65,325.74,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,15,1069759,1304871,1000,1000,1000.00000,36 months,16.29,35.31,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,16,1065775,1299699,10000,10000,10000.00000,36 months,15.27,347.98,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,17,1069971,1304884,3600,3600,3600.00000,36 months,6.03,109.57,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,18,1062474,1294539,6000,6000,6000.00000,36 months,11.71,198.46,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,19,1069742,1304855,9200,9200,9200.00000,36 months,6.03,280.01,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,20,1069740,1284848,20250,20250,19142.16108,60 months,15.27,484.63,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,21,1039153,1269083,21000,21000,21000.00000,36 months,12.42,701.73,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,22,1069710,1304821,10000,10000,10000.00000,36 months,11.71,330.76,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,23,1069700,1304810,10000,10000,10000.00000,36 months,11.71,330.76,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,24,1069559,1304634,6000,6000,6000.00000,36 months,11.71,198.46,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,25,1069697,1273773,15000,15000,15000.00000,36 months,9.91,483.38,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,26,1069800,1304679,15000,15000,8725.00000,36 months,14.27,514.64,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,27,1069657,1304764,5000,5000,5000.00000,60 months,16.77,123.65,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,28,1069799,1304678,4000,4000,4000.00000,36 months,11.71,132.31,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,29,1047704,1278806,8500,8500,8500.00000,36 months,11.71,281.15,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
466255,466255,9776036,11628030,35000,35000,35000.00000,36 months,18.25,1269.73,D,...,NaN,NaN,NaN,NaN,NaN,NaN,153800.0,NaN,NaN,NaN
466256,466256,9835883,9309502,15000,15000,15000.00000,36 months,16.99,534.72,D,...,NaN,NaN,NaN,NaN,NaN,NaN,29300.0,NaN,NaN,NaN
466257,466257,9845880,11697888,12800,12800,12800.00000,36 months,13.53,434.56,B,...,NaN,NaN,NaN,NaN,NaN,NaN,40800.0,NaN,NaN,NaN
466258,466258,9284670,11116818,7000,7000,7000.00000,36 months,9.67,224.79,B,...,NaN,NaN,NaN,NaN,NaN,NaN,5000.0,NaN,NaN,NaN
466259,466259,8646060,10418080,18000,18000,17975.00000,36 months,15.61,629.37,C,...,NaN,NaN,NaN,NaN,NaN,NaN,9200.0,NaN,NaN,NaN
466260,466260,9795940,11647977,24000,24000,24000.00000,36 months,21.48,910.13,E,...,NaN,NaN,NaN,NaN,NaN,NaN,33500.0,NaN,NaN,NaN
466261,466261,9824767,11676888,14400,14400,14375.00000,36 months,13.53,488.88,B,...,NaN,NaN,NaN,NaN,NaN,NaN,38100.0,NaN,NaN,NaN
466262,466262,9825193,11677266,14000,14000,14000.00000,36 months,16.24,493.86,C,...,NaN,NaN,NaN,NaN,NaN,NaN,24400.0,NaN,NaN,NaN
466263,466263,9795013,11647121,15250,15250,15250.00000,36 months,17.57,548.05,D,...,NaN,NaN,NaN,NaN,NaN,NaN,40200.0,NaN,NaN,NaN
466264,466264,9765006,11617106,24000,24000,24000.00000,36 months,13.98,820.04,C,...,NaN,NaN,NaN,NaN,NaN,NaN,20400.0,NaN,NaN,NaN
466265,466265,9774870,11626983,32000,32000,31975.00000,36 months,7.90,1001.29,A,...,NaN,NaN,NaN,NaN,NaN,NaN,30800.0,NaN,NaN,NaN
466266,466266,9794642,2217122,12000,12000,12000.00000,36 months,8.90,381.04,A,...,NaN,NaN,NaN,NaN,NaN,NaN,31900.0,NaN,NaN,NaN
466267,466267,9198304,11060277,10000,10000,10000.00000,36 months,12.85,336.22,B,...,NaN,NaN,NaN,NaN,NaN,NaN,25100.0,NaN,NaN,NaN
466268,466268,9646669,11498434,5000,5000,5000.00000,36 months,22.40,191.99,E,...,NaN,NaN,NaN,NaN,NaN,NaN,32700.0,NaN,NaN,NaN
466269,466269,9505043,11337194,13250,13250,13225.00000,60 months,22.90,372.77,E,...,NaN,NaN,NaN,NaN,NaN,NaN,11300.0,NaN,NaN,NaN
466270,466270,9685861,11537845,10000,10000,10000.00000,36 months,7.90,312.91,A,...,NaN,NaN,NaN,NaN,NaN,NaN,32800.0,NaN,NaN,NaN
466271,466271,9656595,11508352,12000,12000,12000.00000,36 months,16.24,423.31,C,...,NaN,NaN,NaN,NaN,NaN,NaN,27700.0,NaN,NaN,NaN
466272,466272,9686192,11538048,12000,12000,12000.00000,60 months,21.48,327.89,E,...,NaN,NaN,NaN,NaN,NaN,NaN,26500.0,NaN,NaN,NaN
466273,466273,9199716,11061625,6000,6000,6000.00000,36 months,10.99,196.41,B,...,NaN,NaN,NaN,NaN,NaN,NaN,25400.0,NaN,NaN,NaN
466274,466274,9666300,9890240,10000,10000,10000.00000,36 months,11.99,332.10,B,...,NaN,NaN,NaN,NaN,NaN,NaN,17100.0,NaN,NaN,NaN
466275,466275,9715141,11567259,6000,6000,6000.00000,36 months,15.61,209.79,C,...,NaN,NaN,NaN,NaN,NaN,NaN,10500.0,NaN,NaN,NaN
466276,466276,9695736,11547808,8525,8525,8525.00000,60 months,18.25,217.65,D,...,NaN,NaN,NaN,NaN,NaN,NaN,49800.0,NaN,NaN,NaN
466277,466277,9007579,10799568,18000,18000,17975.00000,36 months,7.90,563.23,A,...,NaN,NaN,NaN,NaN,NaN,NaN,50300.0,NaN,NaN,NaN
466278,466278,9745590,11597671,10000,10000,10000.00000,36 months,18.25,362.78,D,...,NaN,NaN,NaN,NaN,NaN,NaN,11100.0,NaN,NaN,NaN
466279,466279,9745484,11597572,15000,15000,15000.00000,36 months,13.53,509.25,B,...,NaN,NaN,NaN,NaN,NaN,NaN,17600.0,NaN,NaN,NaN
466280,466280,8598660,1440975,18400,18400,18400.00000,60 months,14.47,432.64,C,...,NaN,NaN,NaN,NaN,NaN,NaN,29900.0,NaN,NaN,NaN
466281,466281,9684700,11536848,22000,22000,22000.00000,60 months,19.97,582.50,D,...,NaN,NaN,NaN,NaN,NaN,NaN,39400.0,NaN,NaN,NaN
466282,466282,9584776,11436914,20700,20700,20700.00000,60 months,16.99,514.34,D,...,NaN,NaN,NaN,NaN,NaN,NaN,13100.0,NaN,NaN,NaN
466283,466283,9604874,11457002,2000,2000,2000.00000,36 months,7.90,62.59,A,...,NaN,NaN,NaN,NaN,NaN,NaN,53100.0,NaN,NaN,NaN
466284,466284,9199665,11061576,10000,10000,9975.00000,36 months,19.20,367.58,D,...,NaN,NaN,NaN,NaN,NaN,NaN,16000.0,NaN,NaN,NaN

In [6]:
pd.options.display.max_columns = None
#pd.options.display.max_rows = None
# Sets the pandas dataframe options to display all columns/ rows.

In [7]:
loan_data

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
0,0,1077501,1296599,5000,5000,4975.00000,36 months,10.65,162.87,B,B2,NaN,10+ years,RENT,24000.00,Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/22/11 > I need to upgra...,credit_card,Computer,860xx,AZ,27.65,0.0,Jan-85,1.0,NaN,NaN,3.0,0.0,13648,83.70,9.0,f,0.00,0.00,5861.071414,5831.78,5000.00,861.07,0.00,0.00,0.0000,Jan-15,171.62,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1077430,1314167,2500,2500,2500.00000,60 months,15.27,59.83,C,C4,Ryder,< 1 year,RENT,30000.00,Source Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/22/11 > I plan to use t...,car,bike,309xx,GA,1.00,0.0,Apr-99,5.0,NaN,NaN,3.0,0.0,1687,9.40,4.0,f,0.00,0.00,1008.710000,1008.71,456.46,435.17,0.00,117.08,1.1100,Apr-13,119.66,NaN,Sep-13,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,1077175,1313524,2400,2400,2400.00000,36 months,15.96,84.33,C,C5,NaN,10+ years,RENT,12252.00,Not Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,small_business,real estate business,606xx,IL,8.72,0.0,Nov-01,2.0,NaN,NaN,2.0,0.0,2956,98.50,10.0,f,0.00,0.00,3003.653644,3003.65,2400.00,603.65,0.00,0.00,0.0000,Jun-14,649.91,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,1076863,1277178,10000,10000,10000.00000,36 months,13.49,339.31,C,C1,AIR RESOURCES BOARD,10+ years,RENT,49200.00,Source Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/21/11 > to pay for prop...,other,personel,917xx,CA,20.00,0.0,Feb-96,1.0,35.0,NaN,10.0,0.0,5598,21.00,37.0,f,0.00,0.00,12226.302210,12226.30,10000.00,2209.33,16.97,0.00,0.0000,Jan-15,357.48,NaN,Jan-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,1075358,1311748,3000,3000,3000.00000,60 months,12.69,67.79,B,B5,University Medical Group,1 year,RENT,80000.00,Source Verified,Dec-11,Current,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/21/11 > I plan on combi...,other,Personal,972xx,OR,17.94,0.0,Jan-96,0.0,38.0,NaN,15.0,0.0,27783,53.90,38.0,f,766.90,766.90,3242.170000,3242.17,2233.10,1009.07,0.00,0.00,0.0000,Jan-16,67.79,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5,1075269,1311441,5000,5000,5000.00000,36 months,7.90,156.46,A,A4,Veolia Transportaton,3 years,RENT,36000.00,Source Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,wedding,My wedding loan I promise to pay back,852xx,AZ,11.20,0.0,Nov-04,3.0,NaN,NaN,9.0,0.0,7963,28.30,12.0,f,0.00,0.00,5631.377753,5631.38,5000.00,631.38,0.00,0.00,0.0000,Jan-15,161.03,NaN,Sep-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,6,1069639,1304742,7000,7000,7000.00000,60 months,15.96,170.08,C,C5,Southern Star Photography,8 years,RENT,47004.00,Not Verified,Dec-11,Current,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/18/11 > I am planning o...,debt_consolidation,Loan,280xx,NC,23.51,0.0,Jul-05,1.0,NaN,NaN,7.0,0.0,17726,85.60,11.0,f,1889.15,1889.15,8136.840000,8136.84,5110.85,3025.99,0.00,0.00,0.0000,Jan-16,170.08,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,7,1072053,1288686,3000,3000,3000.00000,36 months,18.64,109.43,E,E1,MKC Accounting,9 years,RENT,48000.00,Source Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/16/11 > Downpayment for...,car,Car Downpayment,900xx,CA,5.35,0.0,Jan-07,2.0,NaN,NaN,4.0,0.0,8221,87.50,4.0,f,0.00,0.00,3938.144334,3938.14,3000.00,938.14,0.00,0.00,0.0000,Jan-15,111.34,NaN,Dec-14,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,8,1071795,1306957,5600,5600,5600.00000,60 months,21.28,152.39,F,F2,NaN,4 years,OWN,40000.00,Source Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/21/11 > I own a small h...,small_business,Expand Business & Buy Debt Portfolio,958xx,CA,5.55,0.0,Apr-04,2.0,NaN,NaN,11.0,0.0,5210,32.60,13.0,f,0.00,0.00,646.020000,646.02,162.02,294.94,0.00,189.06,2.0900,Apr-12,152.39,NaN,Aug-12,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,9,1071570,1306721,5375,5375,5350.00000,60 months,12.69,121.45,B,B5,Starbucks,< 1 year,RENT,15000.00,Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/16/11 > I'm trying to b...,other,Building my credit history.,774xx,TX,18.08,0.0,Sep-04,0.0,NaN,NaN,2.0,0.0,9279,36.50,3.0,f,0.00,0.00,1476.190000,1469.34,673.48,533.42,0.00,269.29,2.5200,Nov-12,121.45,NaN,Mar-13,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,10,1070078,1305201,6500,6500,6500.00000,60 months,14.65,153.45,C,C3,Southwest Rural metro,5 years,OWN,72000.00,Not Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/15/11 > I had recived a...,debt_consolidation,High intrest Consolidation,853xx,AZ,16.12,0.0,Jan-98,2.0,NaN,NaN,14.0,0.0,4032,20.60,23.0,f,0.00,0.00,7677.520000,7677.52,6500.00,1177.52,0.00,0.00,0.0000,Jun-13,1655.54,NaN,Dec-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,11,1069908,1305008,12000,12000,12000.00000,36 months,12.69,402.54,B,B5,UCLA,10+ years,OWN,75000.00,Source Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Consolidation,913xx,CA,10.78,0.0,Oct-89,0.0,NaN,NaN,12.0,0.0,23336,67.10,34.0,f,0.00,0.00,13943.080000,13943.08,12000.00,1943.08,0.00,0.00,0.0000,Sep-13,6315.30,NaN,Aug-13,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,12,1064687,1298717,9000,9000,9000.00000,36 months,13.49,305.38,C,C1,Va. Dept of Conservation/Recreation,< 1 year,RENT,30000.00,Source Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/15/11 > Plan to pay off...,debt_consolidation,freedom,245xx,VA,10.08,0.0,Apr-04,1.0,NaN,NaN,4.0,0.0,10452,91.70,9.0,f,0.00,0.00,2270.700000,2270.70,1256.14,570.26,0.00,444.30,4.1600,Jul-12,305.38,NaN,Nov-12,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,13,1069866,1304956,3000,3000,3000.00000,36 months,9.91,96.68,B,B1,Target,3 years,RENT,15000.00,Source Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/19/11 > I intend to pay...,credit_card,citicard fund,606xx,IL,12.56,0.0,Jul-03,2.0,NaN,NaN,11.0,0.0,7323,43.10,11.0,f,0.00,0.00,3478.981915,3478.98,3000.00,478.98,0.00,0.00,0.0000,Jan-15,102.43,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,14,1069057,1303503,10000,10000,10000.00000,36 months,10.65,325.74,B,B2,SFMTA,3 years,RENT,100000.00,Source Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,NaN,other,Other Loan,951xx,CA,7.06,0.0,May-91,2.0,NaN,NaN,14.0,0.0,11997,55.50,29.0,f,0.00,0.00,7471.990000,7471.99,5433.47,1393.42,0.00,645.10,6.3145,Oct-13,325.74,NaN,Mar-14,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,15,1069759,1304871,1000,1000,1000.00000,36 months,16.29,35.31,D,D1,Internal revenue Service,< 1 year,RENT,28000.00,Not Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt Consolidation Loan,641xx,MO,20.31,0.0,Sep-07,1.0,NaN,NaN,11.0,0.0,6524,81.50,23.0,f,0.00,0.00,1270.171106,1270.17,1000.00,270.17,0.00,0.00,0.0000,Jan-15,36.32,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,16,1065775,1299699,10000,10000,10000.00000,36 months,15.27,347.98,C,C4,Chin's Restaurant,4 years,RENT,42000.00,Not Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,home_improvement,Home,921xx,CA,18.60,0.0,Oct-98,2.0,61.0,NaN,14.0,0.0,24043,70.20,28.0,f,0.00,0.00,12519.260450,12519.26,10000.00,2519.26,0.00,0.00,0.0000,Jan-15,370.46,NaN,Apr-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,17,1069971,1304884,3600,3600,3600.00000,36 months,6.03,109.57,A,A1,Duracell,10+ years,MORTGAGE,110000.00,Not Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/15/11 > Payoff other le...,major_purchase,Holiday,067xx,CT,10.52,0.0,Aug-93,0.0,NaN,NaN,20.0,0.0,22836,16.00,42.0,f,0.00,0.00,3785.020000,3785.02,3600.00,185.02,0.00,0.00,0.0000,May-13,583.45,NaN,May-14,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,18,1062474,1294539,6000,6000,6000.00000,36 months,11.71,198.46,B,B3,Connection Inspection,1 year,MORTGAGE,84000.00,Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/16/11 > This is a loan ...,medical,Medical,890xx,UT,18.44,2.0,Oct-03,0.0,8.0,NaN,4.0,0.0,0,37.73,14.0,f,0.00,0.00,7164.499852,7164.50,6000.00,1149.50,15.00,0.00,0.0000,Feb-15,16.98,NaN,Jul-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,19,1069742,1304855,9200,9200,9200.00000,36 months,6.03,280.01,A,A1,Network Interpreting Service,6 years,RENT,77385.19,Not Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,lowerratemeanseasiertogetoutofdebt!,921xx,CA,9.86,0.0,Jan-01,0.0,NaN,NaN,8.0,0.0,7314,23.10,28.0,f,0.00,0.00,9459.960000,9459.96,9200.00,259.96,0.00,0.00,0.0000,Jul-12,8061.10,NaN,Jul-12,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,20,1069740,1284848,20250,20250,19142.16108,60 months,15.27,484.63,C,C4,Archdiocese of Galveston Houston,3 years,RENT,43370.00,Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,After amassing credit card debt through severa...,debt_consolidation,Freedom From Credit Cards,770xx,TX,26.53,0.0,Nov-97,3.0,NaN,NaN,8.0,0.0,17813,85.60,22.0,f,0.00,0.00,27663.042670,25417.68,20250.00,7413.04,0.00,0.00,0.0000,Aug-15,6024.09,NaN,Dec-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,21,1039153,1269083,21000,21000,21000.00000,36 months,12.42,701.73,B,B4,Osram Sylvania,10+ years,RENT,105000.00,Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/16/11 > Decided to clea...,debt_consolidation,Debt Cleanup,335xx,FL,13.22,0.0,Feb-83,0.0,NaN,NaN,7.0,0.0,32135,90.30,38.0,f,0.00,0.00,14025.400000,14025.40,10694.96,3330.44,0.00,0.00,0.0000,Sep-13,701.73,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,22,1069710,1304821,10000,10000,10000.00000,36 months,11.71,330.76,B,B3,Value Air,10+ years,OWN,50000.00,Source Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/17/11 > Have a stable j...,credit_card,Credit Card Loan,799xx,TX,11.18,0.0,Jul-85,0.0,NaN,NaN,8.0,0.0,10056,82.40,21.0,f,0.00,0.00,11902.561570,11902.56,10000.00,1902.56,0.00,0.00,0.0000,Jan-15,349.21,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,23,1069700,1304810,10000,10000,10000.00000,36 months,11.71,330.76,B,B3,Wells Fargo Bank,5 years,RENT,50000.00,Not Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt Consolidation,917xx,CA,16.01,0.0,Apr-03,0.0,NaN,NaN,6.0,0.0,17800,91.80,17.0,f,0.00,0.00,11536.310000,11536.31,10000.00,1536.31,0.00,0.00,0.0000,Oct-13,4942.63,NaN,Mar-14,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,24,1069559,1304634,6000,6000,6000.00000,36 months,11.71,198.46,B,B3,bmg-educational,1 year,RENT,76000.00,Not Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,NaN,major_purchase,cash,900xx,CA,2.40,0.0,Jun-01,1.0,NaN,NaN,7.0,0.0,5963,29.70,7.0,f,0.00,0.00,2050.140000,2050.14,1305.58,475.25,0.00,269.31,2.5700,Oct-12,198.46,NaN,Mar-13,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,25,1069697,1273773,15000,15000,15000.00000,36 months,9.91,483.38,B,B1,Winfield Pathology Consultants,2 years,MORTGAGE,92000.00,Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,credit_card,No more credit card debt!,605xx,IL,29.44,0.0,Feb-02,0.0,NaN,NaN,8.0,0.0,13707,93.90,31.0,f,0.00,0.00,15823.480000,15823.48,15000.00,823.48,0.00,0.00,0.0000,Sep-12,2447.05,NaN,Sep-12,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,26,1069800,1304679,15000,15000,8725.00000,36 months,14.27,514.64,C,C2,nyc transit,9 years,RENT,60000.00,Not Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/15/11 > looking to cons...,debt_consolidation,consolidation,103xx,NY,15.22,0.0,Oct-03,1.0,NaN,NaN,7.0,0.0,5872,57.60,11.0,f,0.00,0.00,0.000000,0.00,0.00,0.00,0.00,0.00,0.0000,NaN,0.00,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,27,1069657,1304764,5000,5000,5000.00000,60 months,16.77,123.65,D,D2,Frito Lay,2 years,RENT,50004.00,Not Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/16/11 > I have a stable...,other,Other,150xx,PA,13.97,3.0,Oct-03,0.0,20.0,NaN,14.0,0.0,4345,59.50,22.0,f,0.00,0.00,1609.120000,1609.12,629.05,719.11,0.00,260.96,2.3000,Dec-12,123.65,NaN,May-13,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,28,1069799,1304678,4000,4000,4000.00000,36 months,11.71,132.31,B,B3,Shands Hospital at the University of Fl,10+ years,MORTGAGE,106000.00,Not Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt Consolidation,326xx,FL,5.63,1.0,Aug-84,0.0,18.0,NaN,12.0,0.0,6110,37.70,44.0,f,0.00,0.00,4484.790000,4484.79,4000.00,484.79,0.00,0.00,0.0000,Apr-13,2638.77,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,29,1047704,1278806,8500,8500,8500.00000,36 months,11.71,281.15,B,B3,Oakridge homes,< 1 year,RENT,25000.00,Source Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/15/11 > My loan is for ...,credit_card,Credit card repayment loan,564xx,MN,12.19,0.0,Nov-06,0.0,NaN,NaN,8.0,0.0,6441,59.10,12.0,f,0.00,0.00,10122.208610,10122.21,8500.00,1622.21,0.00,0.00,0.0000,Dec-14,581.59,NaN,Jan-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
466255,466255,9776036,11628030,35000,35000,35000.00000,36 months,18.25,1269.73,D,D3,NaN,9 years,MORTGAGE,284481.00,Source Verified,Jan-14,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,small_business,Business Loan,618xx,IL,14.59,0.0,Sep-00,1.0,NaN,NaN,19.0,0.0,119663,65.00,35.0,f,0.00,0.00,43086.889390,43086.89,35000.00,8086.89,0.00,0.00,0.0000,Aug-15,20231.99,NaN,Aug-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,383345.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,153800.0,NaN,NaN,NaN
466256,466256,9835883,9309502,15000,15000,15000.00000,36 months,16.99,534.72,D,D1,NaN,NaN,RENT,50000.00,Source Verified,Jan-14,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/12/13 > bill consolidat...,debt_consolidation,debt consolidation,196xx,PA,24.39,0.0,Apr-01,0.0,NaN,NaN,14.0,0.0,24551,83.80,34.0,f,0.00,0.00,5347.100000,5347.10,3436.71,1910.39,0.00,0.00,0.0000,Nov-14,534.72,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,34157.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29300.0,NaN,NaN,NaN
466257,466257,9845880,11697888,12800,12800,12800.00000,36 months,13.53,434.56,B,B5,Chief Information Officer,10+ years,MORTGAGE,113926.00,Verified,Jan-14,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,other,Loan 1,351xx,AL,21.55,0.0,Jul-85,0.0,NaN,NaN,12.0,0.0,20804,51.00,37.0,f,0.00,0.00,15178.050000,15178.05,12800.00,2378.05,0.00,0.00,0.0000,Nov-15,6052.29,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,297745.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40800.0,NaN,NaN,NaN
466258,466258,9284670,11116818,7000,7000,7000.00000,36 months,9.67,224.79,B,B1,Welder,10+ years,RENT,100000.00,Source Verified,Jan-14,Current,n,https://www.lendingclub.com/browse/loanDetail....,NaN,other,Tax Loan,945xx,CA,5.48,0.0,Jun-93,0.0,31.0,NaN,4.0,0.0,2116,42.30,24.0,w,2561.24,2561.24,5394.960000,5394.96,4438.76,956.20,0.00,0.00,0.0000,Jan-16,224.79,Feb-16,Jan-16,0.0,31.0,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,18249.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5000.0,NaN,NaN,NaN
466259,466259,8646060,10418080,18000,18000,17975.00000,36 months,15.61,629.37,C,C4,security guard,4 years,RENT,48000.00,Verified,Jan-14,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt consolidation,333xx,FL,31.05,0.0,Apr-85,1.0,24.0,99.0,9.0,1.0,6126,66.60,18.0,f,0.00,0.00,21379.260500,21349.57,18000.00,3379.26,0.00,0.00,0.0000,Jul-15,10680.56,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,32971.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9200.0,NaN,NaN,NaN
466260,466260,9795940,11647977,24000,24000,24000.00000,36 months,21.48,910.13,E,E2,VP of Operations,10+ years,MORTGAGE,210000.00,Verified,Jan-14,Current,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Lending Club,463xx,IN,12.98,0.0,Sep-97,3.0,NaN,NaN,23.0,0.0,25713,76.80,39.0,w,9750.13,9750.13,21843.120000,21843.12,14249.87,7593.25,0.00,0.00,0.0000,Jan-16,910.13,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,43547.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33500.0,NaN,NaN,NaN

In [8]:
loan_data.head()

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
0,0,1077501,1296599,5000,5000,4975.0,36 months,10.65,162.87,B,B2,NaN,10+ years,RENT,24000.0,Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/22/11 > I need to upgra...,credit_card,Computer,860xx,AZ,27.65,0.0,Jan-85,1.0,NaN,NaN,3.0,0.0,13648,83.7,9.0,f,0.0,0.0,5861.071414,5831.78,5000.00,861.07,0.00,0.00,0.00,Jan-15,171.62,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1077430,1314167,2500,2500,2500.0,60 months,15.27,59.83,C,C4,Ryder,< 1 year,RENT,30000.0,Source Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/22/11 > I plan to use t...,car,bike,309xx,GA,1.00,0.0,Apr-99,5.0,NaN,NaN,3.0,0.0,1687,9.4,4.0,f,0.0,0.0,1008.710000,1008.71,456.46,435.17,0.00,117.08,1.11,Apr-13,119.66,NaN,Sep-13,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,1077175,1313524,2400,2400,2400.0,36 months,15.96,84.33,C,C5,NaN,10+ years,RENT,12252.0,Not Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,small_business,real estate business,606xx,IL,8.72,0.0,Nov-01,2.0,NaN,NaN,2.0,0.0,2956,98.5,10.0,f,0.0,0.0,3003.653644,3003.65,2400.00,603.65,0.00,0.00,0.00,Jun-14,649.91,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,1076863,1277178,10000,10000,10000.0,36 months,13.49,339.31,C,C1,AIR RESOURCES BOARD,10+ years,RENT,49200.0,Source Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/21/11 > to pay for prop...,other,personel,917xx,CA,20.00,0.0,Feb-96,1.0,35.0,NaN,10.0,0.0,5598,21.0,37.0,f,0.0,0.0,12226.302210,12226.30,10000.00,2209.33,16.97,0.00,0.00,Jan-15,357.48,NaN,Jan-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,1075358,1311748,3000,3000,3000.0,60 months,12.69,67.79,B,B5,University Medical Group,1 year,RENT,80000.0,Source Verified,Dec-11,Current,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/21/11 > I plan on combi...,other,Personal,972xx,OR,17.94,0.0,Jan-96,0.0,38.0,NaN,15.0,0.0,27783,53.9,38.0,f,766.9,766.9,3242.170000,3242.17,2233.10,1009.07,0.00,0.00,0.00,Jan-16,67.79,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
loan_data.tail()

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
466280,466280,8598660,1440975,18400,18400,18400.0,60 months,14.47,432.64,C,C2,Financial Advisor,4 years,MORTGAGE,110000.0,Source Verified,Jan-14,Current,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt consolidation,773xx,TX,19.85,0.0,Apr-03,2.0,NaN,NaN,18.0,0.0,23208,77.6,36.0,w,12574.00,12574.00,10383.360000,10383.36,5826.00,4557.36,0.0,0.0,0.0,Jan-16,432.64,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,294998.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29900.0,NaN,NaN,NaN
466281,466281,9684700,11536848,22000,22000,22000.0,60 months,19.97,582.50,D,D5,Chief of Interpretation (Park Ranger),10+ years,MORTGAGE,78000.0,Verified,Jan-14,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt consolidation,377xx,TN,18.45,0.0,Jun-97,5.0,NaN,116.0,18.0,1.0,18238,46.3,30.0,f,0.00,0.00,4677.920000,4677.92,1837.04,2840.88,0.0,0.0,0.0,Dec-14,17.50,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,221830.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39400.0,NaN,NaN,NaN
466282,466282,9584776,11436914,20700,20700,20700.0,60 months,16.99,514.34,D,D1,patrol,7 years,MORTGAGE,46000.0,Verified,Jan-14,Current,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/06/13 > I am going to c...,debt_consolidation,Debt consolidation,458xx,OH,25.65,0.0,Dec-01,2.0,65.0,NaN,18.0,0.0,6688,51.1,43.0,f,14428.31,14428.31,12343.980000,12343.98,6271.69,6072.29,0.0,0.0,0.0,Jan-16,514.34,Feb-16,Dec-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,73598.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13100.0,NaN,NaN,NaN
466283,466283,9604874,11457002,2000,2000,2000.0,36 months,7.90,62.59,A,A4,Server Engineer Lead,3 years,OWN,83000.0,Verified,Jan-14,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,credit_card,Credit card refinancing,913xx,CA,5.39,3.0,Feb-03,1.0,13.0,NaN,21.0,0.0,11404,21.5,27.0,w,0.00,0.00,2126.579838,2126.58,2000.00,126.58,0.0,0.0,0.0,Dec-14,1500.68,NaN,Apr-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,591610.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53100.0,NaN,NaN,NaN
466284,466284,9199665,11061576,10000,10000,9975.0,36 months,19.20,367.58,D,D3,NaN,10+ years,MORTGAGE,46000.0,Verified,Jan-14,Current,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/04/13 > I will like a l...,other,Other,950xx,CA,22.78,1.0,Feb-00,0.0,9.0,NaN,6.0,0.0,11325,70.8,22.0,f,3984.38,3974.41,8821.620000,8799.57,6015.62,2806.00,0.0,0.0,0.0,Jan-16,367.58,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,57477.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16000.0,NaN,NaN,NaN

In [11]:
loan_data.columns.values
# Displays all column names.

array(['Unnamed: 0', 'id', 'member_id', 'loan_amnt', 'funded_amnt',
       'funded_amnt_inv', 'term', 'int_rate', 'installment', 'grade',
       'sub_grade', 'emp_title', 'emp_length', 'home_ownership',
       'annual_inc', 'verification_status', 'issue_d', 'loan_status',
       'pymnt_plan', 'url', 'desc', 'purpose', 'title', 'zip_code',
       'addr_state', 'dti', 'delinq_2yrs', 'earliest_cr_line',
       'inq_last_6mths', 'mths_since_last_delinq',
       'mths_since_last_record', 'open_acc', 'pub_rec', 'revol_bal',
       'revol_util', 'total_acc', 'initial_list_status', 'out_prncp',
       'out_prncp_inv', 'total_pymnt', 'total_pymnt_inv',
       'total_rec_prncp', 'total_rec_int', 'total_rec_late_fee',
       'recoveries', 'collection_recovery_fee', 'last_pymnt_d',
       'last_pymnt_amnt', 'next_pymnt_d', 'last_credit_pull_d',
       'collections_12_mths_ex_med', 'mths_since_last_major_derog',
       'policy_code', 'application_type', 'annual_inc_joint', 'dti_joint',
       'verification_status_joint', 'acc_now_delinq', 'tot_coll_amt',
       'tot_cur_bal', 'open_acc_6m', 'open_il_6m', 'open_il_12m',
       'open_il_24m', 'mths_since_rcnt_il', 'total_bal_il', 'il_util',
       'open_rv_12m', 'open_rv_24m', 'max_bal_bc', 'all_util',
       'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m'],
      dtype=object)

In [12]:
loan_data.info()
# Displays column names, complete (non-missing) cases per column, and datatype per column.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466285 entries, 0 to 466284
Data columns (total 75 columns):
Unnamed: 0                     466285 non-null int64
id                             466285 non-null int64
member_id                      466285 non-null int64
loan_amnt                      466285 non-null int64
funded_amnt                    466285 non-null int64
funded_amnt_inv                466285 non-null float64
term                           466285 non-null object
int_rate                       466285 non-null float64
installment                    466285 non-null float64
grade                          466285 non-null object
sub_grade                      466285 non-null object
emp_title                      438697 non-null object
emp_length                     445277 non-null object
home_ownership                 466285 non-null object
annual_inc                     466281 non-null float64
verification_status            466285 non-null object
issue_d                        466285 non-null object
loan_status                    466285 non-null object
pymnt_plan                     466285 non-null object
url                            466285 non-null object
desc                           125983 non-null object
purpose                        466285 non-null object
title                          466265 non-null object
zip_code                       466285 non-null object
addr_state                     466285 non-null object
dti                            466285 non-null float64
delinq_2yrs                    466256 non-null float64
earliest_cr_line               466256 non-null object
inq_last_6mths                 466256 non-null float64
mths_since_last_delinq         215934 non-null float64
mths_since_last_record         62638 non-null float64
open_acc                       466256 non-null float64
pub_rec                        466256 non-null float64
revol_bal                      466285 non-null int64
revol_util                     465945 non-null float64
total_acc                      466256 non-null float64
initial_list_status            466285 non-null object
out_prncp                      466285 non-null float64
out_prncp_inv                  466285 non-null float64
total_pymnt                    466285 non-null float64
total_pymnt_inv                466285 non-null float64
total_rec_prncp                466285 non-null float64
total_rec_int                  466285 non-null float64
total_rec_late_fee             466285 non-null float64
recoveries                     466285 non-null float64
collection_recovery_fee        466285 non-null float64
last_pymnt_d                   465909 non-null object
last_pymnt_amnt                466285 non-null float64
next_pymnt_d                   239071 non-null object
last_credit_pull_d             466243 non-null object
collections_12_mths_ex_med     466140 non-null float64
mths_since_last_major_derog    98974 non-null float64
policy_code                    466285 non-null int64
application_type               466285 non-null object
annual_inc_joint               0 non-null float64
dti_joint                      0 non-null float64
verification_status_joint      0 non-null float64
acc_now_delinq                 466256 non-null float64
tot_coll_amt                   396009 non-null float64
tot_cur_bal                    396009 non-null float64
open_acc_6m                    0 non-null float64
open_il_6m                     0 non-null float64
open_il_12m                    0 non-null float64
open_il_24m                    0 non-null float64
mths_since_rcnt_il             0 non-null float64
total_bal_il                   0 non-null float64
il_util                        0 non-null float64
open_rv_12m                    0 non-null float64
open_rv_24m                    0 non-null float64
max_bal_bc                     0 non-null float64
all_util                       0 non-null float64
total_rev_hi_lim               396009 non-null float64
inq_fi                         0 non-null float64
total_cu_tl                    0 non-null float64
inq_last_12m                   0 non-null float64
dtypes: float64(46), int64(7), object(22)
memory usage: 266.8+ MB